### ISSUE TITLE
truncated configs folder

### ISSUE THREAD

**Issue by Frontier314** [mixtile/loftq-uboot-next#1]
Machine configuration folder (configs) is truncated, leaving out the Mixtile LoftQ configuration.
It is impossible to build loftq-uboot-next for LoftQ.

**Comment by pengphei** [comment]
As for LOFT-Q, we need you to build it with its own toolchain, which is contained in sunix-build, you have to `source sunxi-build/sunxi_env.sh`, and then build the loftq-dev branch of loftq-uboot-next.

**Comment by pengphei** [comment]
http://mixtile.github.io/en/en-quick-guide.html#debian-building, please refer to this page for more info about how to build linux from scratch.
